INSERT INTO gi.errors (created_at,updated_at,deleted_at,is_valid,updated_id,tranno,`session`,session_id,company_id,short_code,long_code,language_id) VALUES
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0001','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0002','Failed to insert Bdm',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0003','Bdm Successfully Created',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0004','Failed to Get Bdm',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0005','Failed to delete Bdm',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0006','Failed to read Bdm',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0007','Failed to update Bdm',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0008','Failed to Clone Bdm',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0009','Failed to insert Gquote',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0010','Gquote Successfully Created',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0011','Failed to read Gquote',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0012','Type conversion error for page filter sort',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0013','Failed to Clone Gquote',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0014','Failed to Get Gquote',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0015','Failed to update Gquote',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0016','Failed to delete Gquote',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0017','To date is lesser than from date',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0018','Failed to Get Client',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0019','Failed to Get Address',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0020','Enter the Employer Id',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0021','Enter the Address Id',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0022','Mandatory documents are missing',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0023','Invalid frequency parameter',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0024',' Failed to upload file',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0025','Failed to open uploaded file',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0026','Failed to read Excel file',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0027','Failed to get rows from sheet',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0028','Failed to get G0007',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0051','Access Failed',1),
	 (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'K0052','Type conversion error for page filter sort',1),
	 (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'K0053','Failed to read clients',1),
	 (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'K0054','Failed to create medprovider',1),
	 (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'K0055','Successfully created medprovider',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0056','Failed to get medprovider',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0057','Failed to delete medprovider',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0058','Failed to insert medprovider',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0059','Failed to update medprovider',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0060','Failed to clone medprovider',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0061','ToDate is lesser than FromDate',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0062','Successfully created Gquotemember',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0063','Successfully created Member',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0064','Failed to get member',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0065','Failed to delete medprovider',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0066','Failed to update member',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0067','Failed to clone medprovider',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0068','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0069','Failed to create address',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0070',' Failed to get Address',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0071','Failed to Delete Address',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0072','failed to read ',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0073',' Failed to Save Address',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0074','Type conversion error for page filter sort',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0075','Failed to Clone Address',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0076','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0077','Type conversion error for page filter sort',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0078','failed to read agency',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0079','Failed to insert Agency',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0080','agency successfully created',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0081','Failed to Get Agency',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0082','failed to delete agency',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0083','Failed to clone agency',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0084','failed to read agency',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0085','failed to update agency',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0086','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0087','failed to get',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0088','Failed to read businessdate',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0089','Failed to create businessdate',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0090','created businessdate',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0091','failed to delete',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0092','Failed to save businessdate',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0093','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0094','failed to fetch client',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0095','client Dob and Gender are mandatory',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0096','Failed to Create client',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0097','Failed to get client',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0098','Failed to delete client',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0099','Failed to fetch client',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0100','Failed to save client',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0101','client status and dob are mandatory',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0102','failed to create address',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0103','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0104','failed to fetch company',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0105','failed to create company',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0106','failed to get company',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0107','failed to delete company',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0108','failed to save company',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0109','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0110','Failed to get company status',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0111','failed to fetch company status',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0112','Failed to create company status',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0113','Successfully created company status',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0114','failed to delete status',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0115','Failed to save company',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0116','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0117','Failed to fetch error',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0118','failed to create error',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0119','successfully created error',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0120','failed to get error',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0121','failed to delete error',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0122','failed to create error',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0123','failed to fetch error',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0124','failed to save error',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0125','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0126','failed to fetch language ',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0127','failed to create language',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0128','Language created',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0129','failed to get language',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0130','failed to delete language',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0131','failed to create language',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0132','failed to read language',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0133','Access Failed',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0134','Type conversion error for page filter sort',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0135','failed to read medproviderdetail',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0136','failed to create medproviderdetail',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0137','Created medprovider detail',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0138','failed to get medprovider detail',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0139','failed to delete medprovider detail',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0140','failed to clone medprovider',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0141','failed to save medproviderdetail',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0143','Failed to save Qcomments',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0142','failed to get new tranno',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0144','Failed to get Qcomments',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0145','Failed to Create Proof',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0146','Failed to Modified',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0147','Failed to Save Proof',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0148','Failed To Created',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0149','Aadhar is Missing',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0150','Duplicate Aadhar Number',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0151','Member Name is Missing',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0152',' Member DOB is Missing',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0153',' Member DOJ is Missing',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0154',' Member DOR is Missing',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0155','Employer Id is Missing',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0156','Duplicate Employer Id',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0029','Mandatory proof image are missing for document',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0030','Duplicate entry found in QuotationProof fields:',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0031','Duplicate entry found in quoteClauses fields:',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0157','Failed To Bind Medical Requirment Assign data',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0158','Failed To Read Medical Requirment',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'K0159','Failed To Update Medical Requirment',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0034','No data found for the provided ID',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0035','Failed to save Excel file',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0036','Failed to read Excel file',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0037','Failed to insert Invoice',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0038','Invoice Successfully Created',1),
	 (NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL,1,'k0039','Failed to Get Invoice',1);
